{{- $root := . -}}
{{- if .Values.sealedsecrets.enabled }}
{{- range $SealedSecret := .Values.sealedsecrets.keys }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $SealedSecret.name }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    {{- include "common.labels.standard" $root | nindent 4 }}
spec:
  template:
    metadata:
      name: {{ $SealedSecret.name }}
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        {{- include "common.labels.standard" $root | nindent 8 }}
    type: Opaque
  encryptedData:
    {{- range $key, $value := $SealedSecret.encryptedData }}
    {{ $key }}: {{ $value }}
    {{- end }}
{{- end }}
{{- end }}
